### ISSUE TITLE
Netherite items can be crafted from Steel items

### ISSUE THREAD

**Issue by Remyvi12345** [HexagonNico/ReworkedMetals#13]
Hi, I have a suggestion for you to improve due to the fact that Steel Items are a replacement for diamond items, and Netherite Items are very difficult to craft, why not make it so that it would be possible to combine steel armor and netherite ingot in the blacksmith's table, so by making the usual craft of netherite armor :)
(P.S I know that you can turn off the new crafting Netherite armor in Config, but then you will need to look for diamond armor in dungeons or bargain with villagers, which is very difficult, but you can turn on crafting diamond armor in Config, but then the meaning of steel is lost, which is also not very good :)

**Comment by HexagonNico** [comment]
I originally wanted to make all tools feel somehow realistic. For this reason I removed the crafting for diamond tools, since diamond is not a material you would make a tool out of. Same applies to Netherite tools, instead of adding Netherite on top of diamond, it would make more sense if the tools were made directly from Netherite. Plus, I also wanted to give more usage to the smithing table, which, instead of only being used once to upgrade to the next tier of tools, it is used to modify stats for different types of tools.

**Comment by Remyvi12345** [comment]
Hello again! I understood you, but I think it would be nice that when you turn off the "modified crafting Netherite items" you could craft netherite items from steel, or the choice could be banal from steel, or from diamond. I probably got you already, I just say what I think :) Forgive me if I disturb you.

**Comment by HexagonNico** [comment]
Hi. The amount of Netherite you get from smelting has been increased in version 3.0-Pre2 to balance the larger amount you need to craft tools and armor. In the hope that this fixes the problem, I'm closing this issue.
